# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chris/projects/masteroids

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chris/projects/masteroids

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/projects/masteroids/CMakeFiles /home/chris/projects/masteroids/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/projects/masteroids/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named masteroids

# Build rule for target.
masteroids: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 masteroids
.PHONY : masteroids

# fast build rule for target.
masteroids/fast:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/build
.PHONY : masteroids/fast

about.o: about.cpp.o
.PHONY : about.o

# target to build an object file
about.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/about.cpp.o
.PHONY : about.cpp.o

about.i: about.cpp.i
.PHONY : about.i

# target to preprocess a source file
about.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/about.cpp.i
.PHONY : about.cpp.i

about.s: about.cpp.s
.PHONY : about.s

# target to generate assembly for a file
about.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/about.cpp.s
.PHONY : about.cpp.s

alivemonitor.o: alivemonitor.cpp.o
.PHONY : alivemonitor.o

# target to build an object file
alivemonitor.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/alivemonitor.cpp.o
.PHONY : alivemonitor.cpp.o

alivemonitor.i: alivemonitor.cpp.i
.PHONY : alivemonitor.i

# target to preprocess a source file
alivemonitor.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/alivemonitor.cpp.i
.PHONY : alivemonitor.cpp.i

alivemonitor.s: alivemonitor.cpp.s
.PHONY : alivemonitor.s

# target to generate assembly for a file
alivemonitor.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/alivemonitor.cpp.s
.PHONY : alivemonitor.cpp.s

asteroid.o: asteroid.cpp.o
.PHONY : asteroid.o

# target to build an object file
asteroid.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/asteroid.cpp.o
.PHONY : asteroid.cpp.o

asteroid.i: asteroid.cpp.i
.PHONY : asteroid.i

# target to preprocess a source file
asteroid.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/asteroid.cpp.i
.PHONY : asteroid.cpp.i

asteroid.s: asteroid.cpp.s
.PHONY : asteroid.s

# target to generate assembly for a file
asteroid.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/asteroid.cpp.s
.PHONY : asteroid.cpp.s

bullet.o: bullet.cpp.o
.PHONY : bullet.o

# target to build an object file
bullet.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/bullet.cpp.o
.PHONY : bullet.cpp.o

bullet.i: bullet.cpp.i
.PHONY : bullet.i

# target to preprocess a source file
bullet.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/bullet.cpp.i
.PHONY : bullet.cpp.i

bullet.s: bullet.cpp.s
.PHONY : bullet.s

# target to generate assembly for a file
bullet.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/bullet.cpp.s
.PHONY : bullet.cpp.s

controlconf.o: controlconf.cpp.o
.PHONY : controlconf.o

# target to build an object file
controlconf.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/controlconf.cpp.o
.PHONY : controlconf.cpp.o

controlconf.i: controlconf.cpp.i
.PHONY : controlconf.i

# target to preprocess a source file
controlconf.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/controlconf.cpp.i
.PHONY : controlconf.cpp.i

controlconf.s: controlconf.cpp.s
.PHONY : controlconf.s

# target to generate assembly for a file
controlconf.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/controlconf.cpp.s
.PHONY : controlconf.cpp.s

debris.o: debris.cpp.o
.PHONY : debris.o

# target to build an object file
debris.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debris.cpp.o
.PHONY : debris.cpp.o

debris.i: debris.cpp.i
.PHONY : debris.i

# target to preprocess a source file
debris.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debris.cpp.i
.PHONY : debris.cpp.i

debris.s: debris.cpp.s
.PHONY : debris.s

# target to generate assembly for a file
debris.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debris.cpp.s
.PHONY : debris.cpp.s

debrisfountain.o: debrisfountain.cpp.o
.PHONY : debrisfountain.o

# target to build an object file
debrisfountain.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debrisfountain.cpp.o
.PHONY : debrisfountain.cpp.o

debrisfountain.i: debrisfountain.cpp.i
.PHONY : debrisfountain.i

# target to preprocess a source file
debrisfountain.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debrisfountain.cpp.i
.PHONY : debrisfountain.cpp.i

debrisfountain.s: debrisfountain.cpp.s
.PHONY : debrisfountain.s

# target to generate assembly for a file
debrisfountain.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debrisfountain.cpp.s
.PHONY : debrisfountain.cpp.s

direction.o: direction.cpp.o
.PHONY : direction.o

# target to build an object file
direction.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/direction.cpp.o
.PHONY : direction.cpp.o

direction.i: direction.cpp.i
.PHONY : direction.i

# target to preprocess a source file
direction.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/direction.cpp.i
.PHONY : direction.cpp.i

direction.s: direction.cpp.s
.PHONY : direction.s

# target to generate assembly for a file
direction.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/direction.cpp.s
.PHONY : direction.cpp.s

elapsedtimetolive.o: elapsedtimetolive.cpp.o
.PHONY : elapsedtimetolive.o

# target to build an object file
elapsedtimetolive.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/elapsedtimetolive.cpp.o
.PHONY : elapsedtimetolive.cpp.o

elapsedtimetolive.i: elapsedtimetolive.cpp.i
.PHONY : elapsedtimetolive.i

# target to preprocess a source file
elapsedtimetolive.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/elapsedtimetolive.cpp.i
.PHONY : elapsedtimetolive.cpp.i

elapsedtimetolive.s: elapsedtimetolive.cpp.s
.PHONY : elapsedtimetolive.s

# target to generate assembly for a file
elapsedtimetolive.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/elapsedtimetolive.cpp.s
.PHONY : elapsedtimetolive.cpp.s

entitylist.o: entitylist.cpp.o
.PHONY : entitylist.o

# target to build an object file
entitylist.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/entitylist.cpp.o
.PHONY : entitylist.cpp.o

entitylist.i: entitylist.cpp.i
.PHONY : entitylist.i

# target to preprocess a source file
entitylist.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/entitylist.cpp.i
.PHONY : entitylist.cpp.i

entitylist.s: entitylist.cpp.s
.PHONY : entitylist.s

# target to generate assembly for a file
entitylist.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/entitylist.cpp.s
.PHONY : entitylist.cpp.s

gameover.o: gameover.cpp.o
.PHONY : gameover.o

# target to build an object file
gameover.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gameover.cpp.o
.PHONY : gameover.cpp.o

gameover.i: gameover.cpp.i
.PHONY : gameover.i

# target to preprocess a source file
gameover.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gameover.cpp.i
.PHONY : gameover.cpp.i

gameover.s: gameover.cpp.s
.PHONY : gameover.s

# target to generate assembly for a file
gameover.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gameover.cpp.s
.PHONY : gameover.cpp.s

gamescreen.o: gamescreen.cpp.o
.PHONY : gamescreen.o

# target to build an object file
gamescreen.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gamescreen.cpp.o
.PHONY : gamescreen.cpp.o

gamescreen.i: gamescreen.cpp.i
.PHONY : gamescreen.i

# target to preprocess a source file
gamescreen.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gamescreen.cpp.i
.PHONY : gamescreen.cpp.i

gamescreen.s: gamescreen.cpp.s
.PHONY : gamescreen.s

# target to generate assembly for a file
gamescreen.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gamescreen.cpp.s
.PHONY : gamescreen.cpp.s

gametime.o: gametime.cpp.o
.PHONY : gametime.o

# target to build an object file
gametime.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gametime.cpp.o
.PHONY : gametime.cpp.o

gametime.i: gametime.cpp.i
.PHONY : gametime.i

# target to preprocess a source file
gametime.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gametime.cpp.i
.PHONY : gametime.cpp.i

gametime.s: gametime.cpp.s
.PHONY : gametime.s

# target to generate assembly for a file
gametime.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gametime.cpp.s
.PHONY : gametime.cpp.s

gfx/sdlgfx.o: gfx/sdlgfx.cpp.o
.PHONY : gfx/sdlgfx.o

# target to build an object file
gfx/sdlgfx.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gfx/sdlgfx.cpp.o
.PHONY : gfx/sdlgfx.cpp.o

gfx/sdlgfx.i: gfx/sdlgfx.cpp.i
.PHONY : gfx/sdlgfx.i

# target to preprocess a source file
gfx/sdlgfx.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gfx/sdlgfx.cpp.i
.PHONY : gfx/sdlgfx.cpp.i

gfx/sdlgfx.s: gfx/sdlgfx.cpp.s
.PHONY : gfx/sdlgfx.s

# target to generate assembly for a file
gfx/sdlgfx.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gfx/sdlgfx.cpp.s
.PHONY : gfx/sdlgfx.cpp.s

ingame.o: ingame.cpp.o
.PHONY : ingame.o

# target to build an object file
ingame.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/ingame.cpp.o
.PHONY : ingame.cpp.o

ingame.i: ingame.cpp.i
.PHONY : ingame.i

# target to preprocess a source file
ingame.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/ingame.cpp.i
.PHONY : ingame.cpp.i

ingame.s: ingame.cpp.s
.PHONY : ingame.s

# target to generate assembly for a file
ingame.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/ingame.cpp.s
.PHONY : ingame.cpp.s

input/gamepadinputmanager.o: input/gamepadinputmanager.cpp.o
.PHONY : input/gamepadinputmanager.o

# target to build an object file
input/gamepadinputmanager.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/gamepadinputmanager.cpp.o
.PHONY : input/gamepadinputmanager.cpp.o

input/gamepadinputmanager.i: input/gamepadinputmanager.cpp.i
.PHONY : input/gamepadinputmanager.i

# target to preprocess a source file
input/gamepadinputmanager.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/gamepadinputmanager.cpp.i
.PHONY : input/gamepadinputmanager.cpp.i

input/gamepadinputmanager.s: input/gamepadinputmanager.cpp.s
.PHONY : input/gamepadinputmanager.s

# target to generate assembly for a file
input/gamepadinputmanager.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/gamepadinputmanager.cpp.s
.PHONY : input/gamepadinputmanager.cpp.s

input/keyboardsource.o: input/keyboardsource.cpp.o
.PHONY : input/keyboardsource.o

# target to build an object file
input/keyboardsource.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/keyboardsource.cpp.o
.PHONY : input/keyboardsource.cpp.o

input/keyboardsource.i: input/keyboardsource.cpp.i
.PHONY : input/keyboardsource.i

# target to preprocess a source file
input/keyboardsource.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/keyboardsource.cpp.i
.PHONY : input/keyboardsource.cpp.i

input/keyboardsource.s: input/keyboardsource.cpp.s
.PHONY : input/keyboardsource.s

# target to generate assembly for a file
input/keyboardsource.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/keyboardsource.cpp.s
.PHONY : input/keyboardsource.cpp.s

libwiiwrap/gccore.o: libwiiwrap/gccore.c.o
.PHONY : libwiiwrap/gccore.o

# target to build an object file
libwiiwrap/gccore.c.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/gccore.c.o
.PHONY : libwiiwrap/gccore.c.o

libwiiwrap/gccore.i: libwiiwrap/gccore.c.i
.PHONY : libwiiwrap/gccore.i

# target to preprocess a source file
libwiiwrap/gccore.c.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/gccore.c.i
.PHONY : libwiiwrap/gccore.c.i

libwiiwrap/gccore.s: libwiiwrap/gccore.c.s
.PHONY : libwiiwrap/gccore.s

# target to generate assembly for a file
libwiiwrap/gccore.c.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/gccore.c.s
.PHONY : libwiiwrap/gccore.c.s

libwiiwrap/ogc/lwp_watchdog.o: libwiiwrap/ogc/lwp_watchdog.c.o
.PHONY : libwiiwrap/ogc/lwp_watchdog.o

# target to build an object file
libwiiwrap/ogc/lwp_watchdog.c.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogc/lwp_watchdog.c.o
.PHONY : libwiiwrap/ogc/lwp_watchdog.c.o

libwiiwrap/ogc/lwp_watchdog.i: libwiiwrap/ogc/lwp_watchdog.c.i
.PHONY : libwiiwrap/ogc/lwp_watchdog.i

# target to preprocess a source file
libwiiwrap/ogc/lwp_watchdog.c.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogc/lwp_watchdog.c.i
.PHONY : libwiiwrap/ogc/lwp_watchdog.c.i

libwiiwrap/ogc/lwp_watchdog.s: libwiiwrap/ogc/lwp_watchdog.c.s
.PHONY : libwiiwrap/ogc/lwp_watchdog.s

# target to generate assembly for a file
libwiiwrap/ogc/lwp_watchdog.c.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogc/lwp_watchdog.c.s
.PHONY : libwiiwrap/ogc/lwp_watchdog.c.s

libwiiwrap/ogcsys.o: libwiiwrap/ogcsys.c.o
.PHONY : libwiiwrap/ogcsys.o

# target to build an object file
libwiiwrap/ogcsys.c.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogcsys.c.o
.PHONY : libwiiwrap/ogcsys.c.o

libwiiwrap/ogcsys.i: libwiiwrap/ogcsys.c.i
.PHONY : libwiiwrap/ogcsys.i

# target to preprocess a source file
libwiiwrap/ogcsys.c.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogcsys.c.i
.PHONY : libwiiwrap/ogcsys.c.i

libwiiwrap/ogcsys.s: libwiiwrap/ogcsys.c.s
.PHONY : libwiiwrap/ogcsys.s

# target to generate assembly for a file
libwiiwrap/ogcsys.c.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogcsys.c.s
.PHONY : libwiiwrap/ogcsys.c.s

libwiiwrap/wiiuse/wpad.o: libwiiwrap/wiiuse/wpad.c.o
.PHONY : libwiiwrap/wiiuse/wpad.o

# target to build an object file
libwiiwrap/wiiuse/wpad.c.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/wiiuse/wpad.c.o
.PHONY : libwiiwrap/wiiuse/wpad.c.o

libwiiwrap/wiiuse/wpad.i: libwiiwrap/wiiuse/wpad.c.i
.PHONY : libwiiwrap/wiiuse/wpad.i

# target to preprocess a source file
libwiiwrap/wiiuse/wpad.c.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/wiiuse/wpad.c.i
.PHONY : libwiiwrap/wiiuse/wpad.c.i

libwiiwrap/wiiuse/wpad.s: libwiiwrap/wiiuse/wpad.c.s
.PHONY : libwiiwrap/wiiuse/wpad.s

# target to generate assembly for a file
libwiiwrap/wiiuse/wpad.c.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/wiiuse/wpad.c.s
.PHONY : libwiiwrap/wiiuse/wpad.c.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/main.cpp.s
.PHONY : main.cpp.s

menu.o: menu.cpp.o
.PHONY : menu.o

# target to build an object file
menu.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/menu.cpp.o
.PHONY : menu.cpp.o

menu.i: menu.cpp.i
.PHONY : menu.i

# target to preprocess a source file
menu.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/menu.cpp.i
.PHONY : menu.cpp.i

menu.s: menu.cpp.s
.PHONY : menu.s

# target to generate assembly for a file
menu.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/menu.cpp.s
.PHONY : menu.cpp.s

menuscreen.o: menuscreen.cpp.o
.PHONY : menuscreen.o

# target to build an object file
menuscreen.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/menuscreen.cpp.o
.PHONY : menuscreen.cpp.o

menuscreen.i: menuscreen.cpp.i
.PHONY : menuscreen.i

# target to preprocess a source file
menuscreen.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/menuscreen.cpp.i
.PHONY : menuscreen.cpp.i

menuscreen.s: menuscreen.cpp.s
.PHONY : menuscreen.s

# target to generate assembly for a file
menuscreen.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/menuscreen.cpp.s
.PHONY : menuscreen.cpp.s

movers/fixeddirectionmover.o: movers/fixeddirectionmover.cpp.o
.PHONY : movers/fixeddirectionmover.o

# target to build an object file
movers/fixeddirectionmover.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/movers/fixeddirectionmover.cpp.o
.PHONY : movers/fixeddirectionmover.cpp.o

movers/fixeddirectionmover.i: movers/fixeddirectionmover.cpp.i
.PHONY : movers/fixeddirectionmover.i

# target to preprocess a source file
movers/fixeddirectionmover.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/movers/fixeddirectionmover.cpp.i
.PHONY : movers/fixeddirectionmover.cpp.i

movers/fixeddirectionmover.s: movers/fixeddirectionmover.cpp.s
.PHONY : movers/fixeddirectionmover.s

# target to generate assembly for a file
movers/fixeddirectionmover.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/movers/fixeddirectionmover.cpp.s
.PHONY : movers/fixeddirectionmover.cpp.s

options.o: options.cpp.o
.PHONY : options.o

# target to build an object file
options.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/options.cpp.o
.PHONY : options.cpp.o

options.i: options.cpp.i
.PHONY : options.i

# target to preprocess a source file
options.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/options.cpp.i
.PHONY : options.cpp.i

options.s: options.cpp.s
.PHONY : options.s

# target to generate assembly for a file
options.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/options.cpp.s
.PHONY : options.cpp.s

position.o: position.cpp.o
.PHONY : position.o

# target to build an object file
position.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/position.cpp.o
.PHONY : position.cpp.o

position.i: position.cpp.i
.PHONY : position.i

# target to preprocess a source file
position.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/position.cpp.i
.PHONY : position.cpp.i

position.s: position.cpp.s
.PHONY : position.s

# target to generate assembly for a file
position.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/position.cpp.s
.PHONY : position.cpp.s

renderers/optionsrenderer.o: renderers/optionsrenderer.cpp.o
.PHONY : renderers/optionsrenderer.o

# target to build an object file
renderers/optionsrenderer.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/optionsrenderer.cpp.o
.PHONY : renderers/optionsrenderer.cpp.o

renderers/optionsrenderer.i: renderers/optionsrenderer.cpp.i
.PHONY : renderers/optionsrenderer.i

# target to preprocess a source file
renderers/optionsrenderer.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/optionsrenderer.cpp.i
.PHONY : renderers/optionsrenderer.cpp.i

renderers/optionsrenderer.s: renderers/optionsrenderer.cpp.s
.PHONY : renderers/optionsrenderer.s

# target to generate assembly for a file
renderers/optionsrenderer.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/optionsrenderer.cpp.s
.PHONY : renderers/optionsrenderer.cpp.s

renderers/shiprenderer.o: renderers/shiprenderer.cpp.o
.PHONY : renderers/shiprenderer.o

# target to build an object file
renderers/shiprenderer.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/shiprenderer.cpp.o
.PHONY : renderers/shiprenderer.cpp.o

renderers/shiprenderer.i: renderers/shiprenderer.cpp.i
.PHONY : renderers/shiprenderer.i

# target to preprocess a source file
renderers/shiprenderer.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/shiprenderer.cpp.i
.PHONY : renderers/shiprenderer.cpp.i

renderers/shiprenderer.s: renderers/shiprenderer.cpp.s
.PHONY : renderers/shiprenderer.s

# target to generate assembly for a file
renderers/shiprenderer.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/shiprenderer.cpp.s
.PHONY : renderers/shiprenderer.cpp.s

screenmanager.o: screenmanager.cpp.o
.PHONY : screenmanager.o

# target to build an object file
screenmanager.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screenmanager.cpp.o
.PHONY : screenmanager.cpp.o

screenmanager.i: screenmanager.cpp.i
.PHONY : screenmanager.i

# target to preprocess a source file
screenmanager.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screenmanager.cpp.i
.PHONY : screenmanager.cpp.i

screenmanager.s: screenmanager.cpp.s
.PHONY : screenmanager.s

# target to generate assembly for a file
screenmanager.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screenmanager.cpp.s
.PHONY : screenmanager.cpp.s

shape.o: shape.cpp.o
.PHONY : shape.o

# target to build an object file
shape.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/shape.cpp.o
.PHONY : shape.cpp.o

shape.i: shape.cpp.i
.PHONY : shape.i

# target to preprocess a source file
shape.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/shape.cpp.i
.PHONY : shape.cpp.i

shape.s: shape.cpp.s
.PHONY : shape.s

# target to generate assembly for a file
shape.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/shape.cpp.s
.PHONY : shape.cpp.s

ship.o: ship.cpp.o
.PHONY : ship.o

# target to build an object file
ship.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/ship.cpp.o
.PHONY : ship.cpp.o

ship.i: ship.cpp.i
.PHONY : ship.i

# target to preprocess a source file
ship.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/ship.cpp.i
.PHONY : ship.cpp.i

ship.s: ship.cpp.s
.PHONY : ship.s

# target to generate assembly for a file
ship.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/ship.cpp.s
.PHONY : ship.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... masteroids"
	@echo "... rebuild_cache"
	@echo "... about.o"
	@echo "... about.i"
	@echo "... about.s"
	@echo "... alivemonitor.o"
	@echo "... alivemonitor.i"
	@echo "... alivemonitor.s"
	@echo "... asteroid.o"
	@echo "... asteroid.i"
	@echo "... asteroid.s"
	@echo "... bullet.o"
	@echo "... bullet.i"
	@echo "... bullet.s"
	@echo "... controlconf.o"
	@echo "... controlconf.i"
	@echo "... controlconf.s"
	@echo "... debris.o"
	@echo "... debris.i"
	@echo "... debris.s"
	@echo "... debrisfountain.o"
	@echo "... debrisfountain.i"
	@echo "... debrisfountain.s"
	@echo "... direction.o"
	@echo "... direction.i"
	@echo "... direction.s"
	@echo "... elapsedtimetolive.o"
	@echo "... elapsedtimetolive.i"
	@echo "... elapsedtimetolive.s"
	@echo "... entitylist.o"
	@echo "... entitylist.i"
	@echo "... entitylist.s"
	@echo "... gameover.o"
	@echo "... gameover.i"
	@echo "... gameover.s"
	@echo "... gamescreen.o"
	@echo "... gamescreen.i"
	@echo "... gamescreen.s"
	@echo "... gametime.o"
	@echo "... gametime.i"
	@echo "... gametime.s"
	@echo "... gfx/sdlgfx.o"
	@echo "... gfx/sdlgfx.i"
	@echo "... gfx/sdlgfx.s"
	@echo "... ingame.o"
	@echo "... ingame.i"
	@echo "... ingame.s"
	@echo "... input/gamepadinputmanager.o"
	@echo "... input/gamepadinputmanager.i"
	@echo "... input/gamepadinputmanager.s"
	@echo "... input/keyboardsource.o"
	@echo "... input/keyboardsource.i"
	@echo "... input/keyboardsource.s"
	@echo "... libwiiwrap/gccore.o"
	@echo "... libwiiwrap/gccore.i"
	@echo "... libwiiwrap/gccore.s"
	@echo "... libwiiwrap/ogc/lwp_watchdog.o"
	@echo "... libwiiwrap/ogc/lwp_watchdog.i"
	@echo "... libwiiwrap/ogc/lwp_watchdog.s"
	@echo "... libwiiwrap/ogcsys.o"
	@echo "... libwiiwrap/ogcsys.i"
	@echo "... libwiiwrap/ogcsys.s"
	@echo "... libwiiwrap/wiiuse/wpad.o"
	@echo "... libwiiwrap/wiiuse/wpad.i"
	@echo "... libwiiwrap/wiiuse/wpad.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... menu.o"
	@echo "... menu.i"
	@echo "... menu.s"
	@echo "... menuscreen.o"
	@echo "... menuscreen.i"
	@echo "... menuscreen.s"
	@echo "... movers/fixeddirectionmover.o"
	@echo "... movers/fixeddirectionmover.i"
	@echo "... movers/fixeddirectionmover.s"
	@echo "... options.o"
	@echo "... options.i"
	@echo "... options.s"
	@echo "... position.o"
	@echo "... position.i"
	@echo "... position.s"
	@echo "... renderers/optionsrenderer.o"
	@echo "... renderers/optionsrenderer.i"
	@echo "... renderers/optionsrenderer.s"
	@echo "... renderers/shiprenderer.o"
	@echo "... renderers/shiprenderer.i"
	@echo "... renderers/shiprenderer.s"
	@echo "... screenmanager.o"
	@echo "... screenmanager.i"
	@echo "... screenmanager.s"
	@echo "... shape.o"
	@echo "... shape.i"
	@echo "... shape.s"
	@echo "... ship.o"
	@echo "... ship.i"
	@echo "... ship.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

