# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sawczc01/personal/masteroids

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sawczc01/personal/masteroids

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sawczc01/personal/masteroids/CMakeFiles /Users/sawczc01/personal/masteroids/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sawczc01/personal/masteroids/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named masteroids

# Build rule for target.
masteroids: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 masteroids
.PHONY : masteroids

# fast build rule for target.
masteroids/fast:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/build
.PHONY : masteroids/fast

about.o: about.cpp.o
.PHONY : about.o

# target to build an object file
about.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/about.cpp.o
.PHONY : about.cpp.o

about.i: about.cpp.i
.PHONY : about.i

# target to preprocess a source file
about.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/about.cpp.i
.PHONY : about.cpp.i

about.s: about.cpp.s
.PHONY : about.s

# target to generate assembly for a file
about.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/about.cpp.s
.PHONY : about.cpp.s

actor.o: actor.cpp.o
.PHONY : actor.o

# target to build an object file
actor.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/actor.cpp.o
.PHONY : actor.cpp.o

actor.i: actor.cpp.i
.PHONY : actor.i

# target to preprocess a source file
actor.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/actor.cpp.i
.PHONY : actor.cpp.i

actor.s: actor.cpp.s
.PHONY : actor.s

# target to generate assembly for a file
actor.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/actor.cpp.s
.PHONY : actor.cpp.s

alivemonitor.o: alivemonitor.cpp.o
.PHONY : alivemonitor.o

# target to build an object file
alivemonitor.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/alivemonitor.cpp.o
.PHONY : alivemonitor.cpp.o

alivemonitor.i: alivemonitor.cpp.i
.PHONY : alivemonitor.i

# target to preprocess a source file
alivemonitor.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/alivemonitor.cpp.i
.PHONY : alivemonitor.cpp.i

alivemonitor.s: alivemonitor.cpp.s
.PHONY : alivemonitor.s

# target to generate assembly for a file
alivemonitor.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/alivemonitor.cpp.s
.PHONY : alivemonitor.cpp.s

bullet.o: bullet.cpp.o
.PHONY : bullet.o

# target to build an object file
bullet.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/bullet.cpp.o
.PHONY : bullet.cpp.o

bullet.i: bullet.cpp.i
.PHONY : bullet.i

# target to preprocess a source file
bullet.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/bullet.cpp.i
.PHONY : bullet.cpp.i

bullet.s: bullet.cpp.s
.PHONY : bullet.s

# target to generate assembly for a file
bullet.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/bullet.cpp.s
.PHONY : bullet.cpp.s

bulletgenerator.o: bulletgenerator.cpp.o
.PHONY : bulletgenerator.o

# target to build an object file
bulletgenerator.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/bulletgenerator.cpp.o
.PHONY : bulletgenerator.cpp.o

bulletgenerator.i: bulletgenerator.cpp.i
.PHONY : bulletgenerator.i

# target to preprocess a source file
bulletgenerator.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/bulletgenerator.cpp.i
.PHONY : bulletgenerator.cpp.i

bulletgenerator.s: bulletgenerator.cpp.s
.PHONY : bulletgenerator.s

# target to generate assembly for a file
bulletgenerator.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/bulletgenerator.cpp.s
.PHONY : bulletgenerator.cpp.s

controlconf.o: controlconf.cpp.o
.PHONY : controlconf.o

# target to build an object file
controlconf.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/controlconf.cpp.o
.PHONY : controlconf.cpp.o

controlconf.i: controlconf.cpp.i
.PHONY : controlconf.i

# target to preprocess a source file
controlconf.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/controlconf.cpp.i
.PHONY : controlconf.cpp.i

controlconf.s: controlconf.cpp.s
.PHONY : controlconf.s

# target to generate assembly for a file
controlconf.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/controlconf.cpp.s
.PHONY : controlconf.cpp.s

debris.o: debris.cpp.o
.PHONY : debris.o

# target to build an object file
debris.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debris.cpp.o
.PHONY : debris.cpp.o

debris.i: debris.cpp.i
.PHONY : debris.i

# target to preprocess a source file
debris.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debris.cpp.i
.PHONY : debris.cpp.i

debris.s: debris.cpp.s
.PHONY : debris.s

# target to generate assembly for a file
debris.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debris.cpp.s
.PHONY : debris.cpp.s

debrisfountain.o: debrisfountain.cpp.o
.PHONY : debrisfountain.o

# target to build an object file
debrisfountain.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debrisfountain.cpp.o
.PHONY : debrisfountain.cpp.o

debrisfountain.i: debrisfountain.cpp.i
.PHONY : debrisfountain.i

# target to preprocess a source file
debrisfountain.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debrisfountain.cpp.i
.PHONY : debrisfountain.cpp.i

debrisfountain.s: debrisfountain.cpp.s
.PHONY : debrisfountain.s

# target to generate assembly for a file
debrisfountain.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/debrisfountain.cpp.s
.PHONY : debrisfountain.cpp.s

direction.o: direction.cpp.o
.PHONY : direction.o

# target to build an object file
direction.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/direction.cpp.o
.PHONY : direction.cpp.o

direction.i: direction.cpp.i
.PHONY : direction.i

# target to preprocess a source file
direction.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/direction.cpp.i
.PHONY : direction.cpp.i

direction.s: direction.cpp.s
.PHONY : direction.s

# target to generate assembly for a file
direction.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/direction.cpp.s
.PHONY : direction.cpp.s

elapsedtimetolive.o: elapsedtimetolive.cpp.o
.PHONY : elapsedtimetolive.o

# target to build an object file
elapsedtimetolive.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/elapsedtimetolive.cpp.o
.PHONY : elapsedtimetolive.cpp.o

elapsedtimetolive.i: elapsedtimetolive.cpp.i
.PHONY : elapsedtimetolive.i

# target to preprocess a source file
elapsedtimetolive.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/elapsedtimetolive.cpp.i
.PHONY : elapsedtimetolive.cpp.i

elapsedtimetolive.s: elapsedtimetolive.cpp.s
.PHONY : elapsedtimetolive.s

# target to generate assembly for a file
elapsedtimetolive.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/elapsedtimetolive.cpp.s
.PHONY : elapsedtimetolive.cpp.s

entitylist.o: entitylist.cpp.o
.PHONY : entitylist.o

# target to build an object file
entitylist.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/entitylist.cpp.o
.PHONY : entitylist.cpp.o

entitylist.i: entitylist.cpp.i
.PHONY : entitylist.i

# target to preprocess a source file
entitylist.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/entitylist.cpp.i
.PHONY : entitylist.cpp.i

entitylist.s: entitylist.cpp.s
.PHONY : entitylist.s

# target to generate assembly for a file
entitylist.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/entitylist.cpp.s
.PHONY : entitylist.cpp.s

gameover.o: gameover.cpp.o
.PHONY : gameover.o

# target to build an object file
gameover.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gameover.cpp.o
.PHONY : gameover.cpp.o

gameover.i: gameover.cpp.i
.PHONY : gameover.i

# target to preprocess a source file
gameover.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gameover.cpp.i
.PHONY : gameover.cpp.i

gameover.s: gameover.cpp.s
.PHONY : gameover.s

# target to generate assembly for a file
gameover.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gameover.cpp.s
.PHONY : gameover.cpp.s

gametime.o: gametime.cpp.o
.PHONY : gametime.o

# target to build an object file
gametime.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gametime.cpp.o
.PHONY : gametime.cpp.o

gametime.i: gametime.cpp.i
.PHONY : gametime.i

# target to preprocess a source file
gametime.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gametime.cpp.i
.PHONY : gametime.cpp.i

gametime.s: gametime.cpp.s
.PHONY : gametime.s

# target to generate assembly for a file
gametime.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gametime.cpp.s
.PHONY : gametime.cpp.s

gfx/sdlgfx.o: gfx/sdlgfx.cpp.o
.PHONY : gfx/sdlgfx.o

# target to build an object file
gfx/sdlgfx.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gfx/sdlgfx.cpp.o
.PHONY : gfx/sdlgfx.cpp.o

gfx/sdlgfx.i: gfx/sdlgfx.cpp.i
.PHONY : gfx/sdlgfx.i

# target to preprocess a source file
gfx/sdlgfx.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gfx/sdlgfx.cpp.i
.PHONY : gfx/sdlgfx.cpp.i

gfx/sdlgfx.s: gfx/sdlgfx.cpp.s
.PHONY : gfx/sdlgfx.s

# target to generate assembly for a file
gfx/sdlgfx.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gfx/sdlgfx.cpp.s
.PHONY : gfx/sdlgfx.cpp.s

gfx/sdlresourcemanager.o: gfx/sdlresourcemanager.cpp.o
.PHONY : gfx/sdlresourcemanager.o

# target to build an object file
gfx/sdlresourcemanager.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gfx/sdlresourcemanager.cpp.o
.PHONY : gfx/sdlresourcemanager.cpp.o

gfx/sdlresourcemanager.i: gfx/sdlresourcemanager.cpp.i
.PHONY : gfx/sdlresourcemanager.i

# target to preprocess a source file
gfx/sdlresourcemanager.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gfx/sdlresourcemanager.cpp.i
.PHONY : gfx/sdlresourcemanager.cpp.i

gfx/sdlresourcemanager.s: gfx/sdlresourcemanager.cpp.s
.PHONY : gfx/sdlresourcemanager.s

# target to generate assembly for a file
gfx/sdlresourcemanager.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/gfx/sdlresourcemanager.cpp.s
.PHONY : gfx/sdlresourcemanager.cpp.s

input/gamepadinputmanager.o: input/gamepadinputmanager.cpp.o
.PHONY : input/gamepadinputmanager.o

# target to build an object file
input/gamepadinputmanager.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/gamepadinputmanager.cpp.o
.PHONY : input/gamepadinputmanager.cpp.o

input/gamepadinputmanager.i: input/gamepadinputmanager.cpp.i
.PHONY : input/gamepadinputmanager.i

# target to preprocess a source file
input/gamepadinputmanager.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/gamepadinputmanager.cpp.i
.PHONY : input/gamepadinputmanager.cpp.i

input/gamepadinputmanager.s: input/gamepadinputmanager.cpp.s
.PHONY : input/gamepadinputmanager.s

# target to generate assembly for a file
input/gamepadinputmanager.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/gamepadinputmanager.cpp.s
.PHONY : input/gamepadinputmanager.cpp.s

input/keyboardsource.o: input/keyboardsource.cpp.o
.PHONY : input/keyboardsource.o

# target to build an object file
input/keyboardsource.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/keyboardsource.cpp.o
.PHONY : input/keyboardsource.cpp.o

input/keyboardsource.i: input/keyboardsource.cpp.i
.PHONY : input/keyboardsource.i

# target to preprocess a source file
input/keyboardsource.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/keyboardsource.cpp.i
.PHONY : input/keyboardsource.cpp.i

input/keyboardsource.s: input/keyboardsource.cpp.s
.PHONY : input/keyboardsource.s

# target to generate assembly for a file
input/keyboardsource.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/input/keyboardsource.cpp.s
.PHONY : input/keyboardsource.cpp.s

libwiiwrap/gccore.o: libwiiwrap/gccore.cpp.o
.PHONY : libwiiwrap/gccore.o

# target to build an object file
libwiiwrap/gccore.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/gccore.cpp.o
.PHONY : libwiiwrap/gccore.cpp.o

libwiiwrap/gccore.i: libwiiwrap/gccore.cpp.i
.PHONY : libwiiwrap/gccore.i

# target to preprocess a source file
libwiiwrap/gccore.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/gccore.cpp.i
.PHONY : libwiiwrap/gccore.cpp.i

libwiiwrap/gccore.s: libwiiwrap/gccore.cpp.s
.PHONY : libwiiwrap/gccore.s

# target to generate assembly for a file
libwiiwrap/gccore.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/gccore.cpp.s
.PHONY : libwiiwrap/gccore.cpp.s

libwiiwrap/ogc/lwp_watchdog.o: libwiiwrap/ogc/lwp_watchdog.cpp.o
.PHONY : libwiiwrap/ogc/lwp_watchdog.o

# target to build an object file
libwiiwrap/ogc/lwp_watchdog.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogc/lwp_watchdog.cpp.o
.PHONY : libwiiwrap/ogc/lwp_watchdog.cpp.o

libwiiwrap/ogc/lwp_watchdog.i: libwiiwrap/ogc/lwp_watchdog.cpp.i
.PHONY : libwiiwrap/ogc/lwp_watchdog.i

# target to preprocess a source file
libwiiwrap/ogc/lwp_watchdog.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogc/lwp_watchdog.cpp.i
.PHONY : libwiiwrap/ogc/lwp_watchdog.cpp.i

libwiiwrap/ogc/lwp_watchdog.s: libwiiwrap/ogc/lwp_watchdog.cpp.s
.PHONY : libwiiwrap/ogc/lwp_watchdog.s

# target to generate assembly for a file
libwiiwrap/ogc/lwp_watchdog.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogc/lwp_watchdog.cpp.s
.PHONY : libwiiwrap/ogc/lwp_watchdog.cpp.s

libwiiwrap/ogcsys.o: libwiiwrap/ogcsys.cpp.o
.PHONY : libwiiwrap/ogcsys.o

# target to build an object file
libwiiwrap/ogcsys.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogcsys.cpp.o
.PHONY : libwiiwrap/ogcsys.cpp.o

libwiiwrap/ogcsys.i: libwiiwrap/ogcsys.cpp.i
.PHONY : libwiiwrap/ogcsys.i

# target to preprocess a source file
libwiiwrap/ogcsys.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogcsys.cpp.i
.PHONY : libwiiwrap/ogcsys.cpp.i

libwiiwrap/ogcsys.s: libwiiwrap/ogcsys.cpp.s
.PHONY : libwiiwrap/ogcsys.s

# target to generate assembly for a file
libwiiwrap/ogcsys.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/ogcsys.cpp.s
.PHONY : libwiiwrap/ogcsys.cpp.s

libwiiwrap/wiiuse/wpad.o: libwiiwrap/wiiuse/wpad.cpp.o
.PHONY : libwiiwrap/wiiuse/wpad.o

# target to build an object file
libwiiwrap/wiiuse/wpad.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/wiiuse/wpad.cpp.o
.PHONY : libwiiwrap/wiiuse/wpad.cpp.o

libwiiwrap/wiiuse/wpad.i: libwiiwrap/wiiuse/wpad.cpp.i
.PHONY : libwiiwrap/wiiuse/wpad.i

# target to preprocess a source file
libwiiwrap/wiiuse/wpad.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/wiiuse/wpad.cpp.i
.PHONY : libwiiwrap/wiiuse/wpad.cpp.i

libwiiwrap/wiiuse/wpad.s: libwiiwrap/wiiuse/wpad.cpp.s
.PHONY : libwiiwrap/wiiuse/wpad.s

# target to generate assembly for a file
libwiiwrap/wiiuse/wpad.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/libwiiwrap/wiiuse/wpad.cpp.s
.PHONY : libwiiwrap/wiiuse/wpad.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/main.cpp.s
.PHONY : main.cpp.s

menu.o: menu.cpp.o
.PHONY : menu.o

# target to build an object file
menu.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/menu.cpp.o
.PHONY : menu.cpp.o

menu.i: menu.cpp.i
.PHONY : menu.i

# target to preprocess a source file
menu.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/menu.cpp.i
.PHONY : menu.cpp.i

menu.s: menu.cpp.s
.PHONY : menu.s

# target to generate assembly for a file
menu.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/menu.cpp.s
.PHONY : menu.cpp.s

movers/fixeddirectionmover.o: movers/fixeddirectionmover.cpp.o
.PHONY : movers/fixeddirectionmover.o

# target to build an object file
movers/fixeddirectionmover.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/movers/fixeddirectionmover.cpp.o
.PHONY : movers/fixeddirectionmover.cpp.o

movers/fixeddirectionmover.i: movers/fixeddirectionmover.cpp.i
.PHONY : movers/fixeddirectionmover.i

# target to preprocess a source file
movers/fixeddirectionmover.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/movers/fixeddirectionmover.cpp.i
.PHONY : movers/fixeddirectionmover.cpp.i

movers/fixeddirectionmover.s: movers/fixeddirectionmover.cpp.s
.PHONY : movers/fixeddirectionmover.s

# target to generate assembly for a file
movers/fixeddirectionmover.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/movers/fixeddirectionmover.cpp.s
.PHONY : movers/fixeddirectionmover.cpp.s

options.o: options.cpp.o
.PHONY : options.o

# target to build an object file
options.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/options.cpp.o
.PHONY : options.cpp.o

options.i: options.cpp.i
.PHONY : options.i

# target to preprocess a source file
options.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/options.cpp.i
.PHONY : options.cpp.i

options.s: options.cpp.s
.PHONY : options.s

# target to generate assembly for a file
options.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/options.cpp.s
.PHONY : options.cpp.s

pausedialog.o: pausedialog.cpp.o
.PHONY : pausedialog.o

# target to build an object file
pausedialog.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/pausedialog.cpp.o
.PHONY : pausedialog.cpp.o

pausedialog.i: pausedialog.cpp.i
.PHONY : pausedialog.i

# target to preprocess a source file
pausedialog.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/pausedialog.cpp.i
.PHONY : pausedialog.cpp.i

pausedialog.s: pausedialog.cpp.s
.PHONY : pausedialog.s

# target to generate assembly for a file
pausedialog.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/pausedialog.cpp.s
.PHONY : pausedialog.cpp.s

playermanager.o: playermanager.cpp.o
.PHONY : playermanager.o

# target to build an object file
playermanager.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/playermanager.cpp.o
.PHONY : playermanager.cpp.o

playermanager.i: playermanager.cpp.i
.PHONY : playermanager.i

# target to preprocess a source file
playermanager.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/playermanager.cpp.i
.PHONY : playermanager.cpp.i

playermanager.s: playermanager.cpp.s
.PHONY : playermanager.s

# target to generate assembly for a file
playermanager.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/playermanager.cpp.s
.PHONY : playermanager.cpp.s

position.o: position.cpp.o
.PHONY : position.o

# target to build an object file
position.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/position.cpp.o
.PHONY : position.cpp.o

position.i: position.cpp.i
.PHONY : position.i

# target to preprocess a source file
position.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/position.cpp.i
.PHONY : position.cpp.i

position.s: position.cpp.s
.PHONY : position.s

# target to generate assembly for a file
position.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/position.cpp.s
.PHONY : position.cpp.s

renderers/gameoverrenderer.o: renderers/gameoverrenderer.cpp.o
.PHONY : renderers/gameoverrenderer.o

# target to build an object file
renderers/gameoverrenderer.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/gameoverrenderer.cpp.o
.PHONY : renderers/gameoverrenderer.cpp.o

renderers/gameoverrenderer.i: renderers/gameoverrenderer.cpp.i
.PHONY : renderers/gameoverrenderer.i

# target to preprocess a source file
renderers/gameoverrenderer.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/gameoverrenderer.cpp.i
.PHONY : renderers/gameoverrenderer.cpp.i

renderers/gameoverrenderer.s: renderers/gameoverrenderer.cpp.s
.PHONY : renderers/gameoverrenderer.s

# target to generate assembly for a file
renderers/gameoverrenderer.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/gameoverrenderer.cpp.s
.PHONY : renderers/gameoverrenderer.cpp.s

renderers/livesrenderer.o: renderers/livesrenderer.cpp.o
.PHONY : renderers/livesrenderer.o

# target to build an object file
renderers/livesrenderer.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/livesrenderer.cpp.o
.PHONY : renderers/livesrenderer.cpp.o

renderers/livesrenderer.i: renderers/livesrenderer.cpp.i
.PHONY : renderers/livesrenderer.i

# target to preprocess a source file
renderers/livesrenderer.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/livesrenderer.cpp.i
.PHONY : renderers/livesrenderer.cpp.i

renderers/livesrenderer.s: renderers/livesrenderer.cpp.s
.PHONY : renderers/livesrenderer.s

# target to generate assembly for a file
renderers/livesrenderer.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/livesrenderer.cpp.s
.PHONY : renderers/livesrenderer.cpp.s

renderers/optionsrenderer.o: renderers/optionsrenderer.cpp.o
.PHONY : renderers/optionsrenderer.o

# target to build an object file
renderers/optionsrenderer.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/optionsrenderer.cpp.o
.PHONY : renderers/optionsrenderer.cpp.o

renderers/optionsrenderer.i: renderers/optionsrenderer.cpp.i
.PHONY : renderers/optionsrenderer.i

# target to preprocess a source file
renderers/optionsrenderer.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/optionsrenderer.cpp.i
.PHONY : renderers/optionsrenderer.cpp.i

renderers/optionsrenderer.s: renderers/optionsrenderer.cpp.s
.PHONY : renderers/optionsrenderer.s

# target to generate assembly for a file
renderers/optionsrenderer.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/optionsrenderer.cpp.s
.PHONY : renderers/optionsrenderer.cpp.s

renderers/pausedialogrenderer.o: renderers/pausedialogrenderer.cpp.o
.PHONY : renderers/pausedialogrenderer.o

# target to build an object file
renderers/pausedialogrenderer.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/pausedialogrenderer.cpp.o
.PHONY : renderers/pausedialogrenderer.cpp.o

renderers/pausedialogrenderer.i: renderers/pausedialogrenderer.cpp.i
.PHONY : renderers/pausedialogrenderer.i

# target to preprocess a source file
renderers/pausedialogrenderer.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/pausedialogrenderer.cpp.i
.PHONY : renderers/pausedialogrenderer.cpp.i

renderers/pausedialogrenderer.s: renderers/pausedialogrenderer.cpp.s
.PHONY : renderers/pausedialogrenderer.s

# target to generate assembly for a file
renderers/pausedialogrenderer.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/pausedialogrenderer.cpp.s
.PHONY : renderers/pausedialogrenderer.cpp.s

renderers/scorerenderer.o: renderers/scorerenderer.cpp.o
.PHONY : renderers/scorerenderer.o

# target to build an object file
renderers/scorerenderer.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/scorerenderer.cpp.o
.PHONY : renderers/scorerenderer.cpp.o

renderers/scorerenderer.i: renderers/scorerenderer.cpp.i
.PHONY : renderers/scorerenderer.i

# target to preprocess a source file
renderers/scorerenderer.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/scorerenderer.cpp.i
.PHONY : renderers/scorerenderer.cpp.i

renderers/scorerenderer.s: renderers/scorerenderer.cpp.s
.PHONY : renderers/scorerenderer.s

# target to generate assembly for a file
renderers/scorerenderer.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/scorerenderer.cpp.s
.PHONY : renderers/scorerenderer.cpp.s

renderers/shiprenderer.o: renderers/shiprenderer.cpp.o
.PHONY : renderers/shiprenderer.o

# target to build an object file
renderers/shiprenderer.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/shiprenderer.cpp.o
.PHONY : renderers/shiprenderer.cpp.o

renderers/shiprenderer.i: renderers/shiprenderer.cpp.i
.PHONY : renderers/shiprenderer.i

# target to preprocess a source file
renderers/shiprenderer.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/shiprenderer.cpp.i
.PHONY : renderers/shiprenderer.cpp.i

renderers/shiprenderer.s: renderers/shiprenderer.cpp.s
.PHONY : renderers/shiprenderer.s

# target to generate assembly for a file
renderers/shiprenderer.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/renderers/shiprenderer.cpp.s
.PHONY : renderers/shiprenderer.cpp.s

screenmanager.o: screenmanager.cpp.o
.PHONY : screenmanager.o

# target to build an object file
screenmanager.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screenmanager.cpp.o
.PHONY : screenmanager.cpp.o

screenmanager.i: screenmanager.cpp.i
.PHONY : screenmanager.i

# target to preprocess a source file
screenmanager.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screenmanager.cpp.i
.PHONY : screenmanager.cpp.i

screenmanager.s: screenmanager.cpp.s
.PHONY : screenmanager.s

# target to generate assembly for a file
screenmanager.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screenmanager.cpp.s
.PHONY : screenmanager.cpp.s

screens/gameoverscreen.o: screens/gameoverscreen.cpp.o
.PHONY : screens/gameoverscreen.o

# target to build an object file
screens/gameoverscreen.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screens/gameoverscreen.cpp.o
.PHONY : screens/gameoverscreen.cpp.o

screens/gameoverscreen.i: screens/gameoverscreen.cpp.i
.PHONY : screens/gameoverscreen.i

# target to preprocess a source file
screens/gameoverscreen.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screens/gameoverscreen.cpp.i
.PHONY : screens/gameoverscreen.cpp.i

screens/gameoverscreen.s: screens/gameoverscreen.cpp.s
.PHONY : screens/gameoverscreen.s

# target to generate assembly for a file
screens/gameoverscreen.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screens/gameoverscreen.cpp.s
.PHONY : screens/gameoverscreen.cpp.s

screens/gamescreen.o: screens/gamescreen.cpp.o
.PHONY : screens/gamescreen.o

# target to build an object file
screens/gamescreen.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screens/gamescreen.cpp.o
.PHONY : screens/gamescreen.cpp.o

screens/gamescreen.i: screens/gamescreen.cpp.i
.PHONY : screens/gamescreen.i

# target to preprocess a source file
screens/gamescreen.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screens/gamescreen.cpp.i
.PHONY : screens/gamescreen.cpp.i

screens/gamescreen.s: screens/gamescreen.cpp.s
.PHONY : screens/gamescreen.s

# target to generate assembly for a file
screens/gamescreen.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screens/gamescreen.cpp.s
.PHONY : screens/gamescreen.cpp.s

screens/menuscreen.o: screens/menuscreen.cpp.o
.PHONY : screens/menuscreen.o

# target to build an object file
screens/menuscreen.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screens/menuscreen.cpp.o
.PHONY : screens/menuscreen.cpp.o

screens/menuscreen.i: screens/menuscreen.cpp.i
.PHONY : screens/menuscreen.i

# target to preprocess a source file
screens/menuscreen.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screens/menuscreen.cpp.i
.PHONY : screens/menuscreen.cpp.i

screens/menuscreen.s: screens/menuscreen.cpp.s
.PHONY : screens/menuscreen.s

# target to generate assembly for a file
screens/menuscreen.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/screens/menuscreen.cpp.s
.PHONY : screens/menuscreen.cpp.s

shape.o: shape.cpp.o
.PHONY : shape.o

# target to build an object file
shape.cpp.o:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/shape.cpp.o
.PHONY : shape.cpp.o

shape.i: shape.cpp.i
.PHONY : shape.i

# target to preprocess a source file
shape.cpp.i:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/shape.cpp.i
.PHONY : shape.cpp.i

shape.s: shape.cpp.s
.PHONY : shape.s

# target to generate assembly for a file
shape.cpp.s:
	$(MAKE) -f CMakeFiles/masteroids.dir/build.make CMakeFiles/masteroids.dir/shape.cpp.s
.PHONY : shape.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... masteroids"
	@echo "... about.o"
	@echo "... about.i"
	@echo "... about.s"
	@echo "... actor.o"
	@echo "... actor.i"
	@echo "... actor.s"
	@echo "... alivemonitor.o"
	@echo "... alivemonitor.i"
	@echo "... alivemonitor.s"
	@echo "... bullet.o"
	@echo "... bullet.i"
	@echo "... bullet.s"
	@echo "... bulletgenerator.o"
	@echo "... bulletgenerator.i"
	@echo "... bulletgenerator.s"
	@echo "... controlconf.o"
	@echo "... controlconf.i"
	@echo "... controlconf.s"
	@echo "... debris.o"
	@echo "... debris.i"
	@echo "... debris.s"
	@echo "... debrisfountain.o"
	@echo "... debrisfountain.i"
	@echo "... debrisfountain.s"
	@echo "... direction.o"
	@echo "... direction.i"
	@echo "... direction.s"
	@echo "... elapsedtimetolive.o"
	@echo "... elapsedtimetolive.i"
	@echo "... elapsedtimetolive.s"
	@echo "... entitylist.o"
	@echo "... entitylist.i"
	@echo "... entitylist.s"
	@echo "... gameover.o"
	@echo "... gameover.i"
	@echo "... gameover.s"
	@echo "... gametime.o"
	@echo "... gametime.i"
	@echo "... gametime.s"
	@echo "... gfx/sdlgfx.o"
	@echo "... gfx/sdlgfx.i"
	@echo "... gfx/sdlgfx.s"
	@echo "... gfx/sdlresourcemanager.o"
	@echo "... gfx/sdlresourcemanager.i"
	@echo "... gfx/sdlresourcemanager.s"
	@echo "... input/gamepadinputmanager.o"
	@echo "... input/gamepadinputmanager.i"
	@echo "... input/gamepadinputmanager.s"
	@echo "... input/keyboardsource.o"
	@echo "... input/keyboardsource.i"
	@echo "... input/keyboardsource.s"
	@echo "... libwiiwrap/gccore.o"
	@echo "... libwiiwrap/gccore.i"
	@echo "... libwiiwrap/gccore.s"
	@echo "... libwiiwrap/ogc/lwp_watchdog.o"
	@echo "... libwiiwrap/ogc/lwp_watchdog.i"
	@echo "... libwiiwrap/ogc/lwp_watchdog.s"
	@echo "... libwiiwrap/ogcsys.o"
	@echo "... libwiiwrap/ogcsys.i"
	@echo "... libwiiwrap/ogcsys.s"
	@echo "... libwiiwrap/wiiuse/wpad.o"
	@echo "... libwiiwrap/wiiuse/wpad.i"
	@echo "... libwiiwrap/wiiuse/wpad.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... menu.o"
	@echo "... menu.i"
	@echo "... menu.s"
	@echo "... movers/fixeddirectionmover.o"
	@echo "... movers/fixeddirectionmover.i"
	@echo "... movers/fixeddirectionmover.s"
	@echo "... options.o"
	@echo "... options.i"
	@echo "... options.s"
	@echo "... pausedialog.o"
	@echo "... pausedialog.i"
	@echo "... pausedialog.s"
	@echo "... playermanager.o"
	@echo "... playermanager.i"
	@echo "... playermanager.s"
	@echo "... position.o"
	@echo "... position.i"
	@echo "... position.s"
	@echo "... renderers/gameoverrenderer.o"
	@echo "... renderers/gameoverrenderer.i"
	@echo "... renderers/gameoverrenderer.s"
	@echo "... renderers/livesrenderer.o"
	@echo "... renderers/livesrenderer.i"
	@echo "... renderers/livesrenderer.s"
	@echo "... renderers/optionsrenderer.o"
	@echo "... renderers/optionsrenderer.i"
	@echo "... renderers/optionsrenderer.s"
	@echo "... renderers/pausedialogrenderer.o"
	@echo "... renderers/pausedialogrenderer.i"
	@echo "... renderers/pausedialogrenderer.s"
	@echo "... renderers/scorerenderer.o"
	@echo "... renderers/scorerenderer.i"
	@echo "... renderers/scorerenderer.s"
	@echo "... renderers/shiprenderer.o"
	@echo "... renderers/shiprenderer.i"
	@echo "... renderers/shiprenderer.s"
	@echo "... screenmanager.o"
	@echo "... screenmanager.i"
	@echo "... screenmanager.s"
	@echo "... screens/gameoverscreen.o"
	@echo "... screens/gameoverscreen.i"
	@echo "... screens/gameoverscreen.s"
	@echo "... screens/gamescreen.o"
	@echo "... screens/gamescreen.i"
	@echo "... screens/gamescreen.s"
	@echo "... screens/menuscreen.o"
	@echo "... screens/menuscreen.i"
	@echo "... screens/menuscreen.s"
	@echo "... shape.o"
	@echo "... shape.i"
	@echo "... shape.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

