/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _regularfont_h_
#define _regularfont_h_
//---------------------------------------------------------------------------------
extern const unsigned char regularfont[];
extern const int regularfont_size;
//---------------------------------------------------------------------------------
#endif //_regularfont_h_
//---------------------------------------------------------------------------------
